export const Organizationsdata = {
  orman: {
    logo: "../../../public/ormanlogo.png",
    history: "هي منظمة مصرية أهلية، لا تهدف إلى الربح ولا تخضع لضرائب على التبرعات، أنشئت عام 1993 مقيدة برقم 803 مركزية بوزارة التضامن الاجتماعي، تهدف إلى خدمة الفئات الأكثر احتياجا، دون أي تمييز ديني أو سياسي، وتعتمد الجمعية في تمويلها على التبرعات العينية والنقدية من المصريين داخل مصر وخارجها.",
    data: [
      {
        id: 1,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "اطعام",
        secation: "Donations",
        organization: "orman",
      },
      {
        id: 2,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "اطعام",
        secation: "Donations",
        organization: "orman",
      },
      {
        id: 3,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        place: "المنوفيه",
        number: "01277840406",
        tragetprice: 2700,
        pricenow: 1000,
        category: "اطعام",
        organization: "orman",
        secation: "Donations",
      },
      {
        id: 4,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        organization: "orman",
        category: "اطعام",
        secation: "Donations",
      },
      {
        id: 5,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        organization: "orman",
        category: "اطعام",
        secation: "Donations",
      },
      {
        id: 6,
        title: "كفاله ايتام",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "كفاله",
        organization: "orman",
        secation: "Donations",
      },
      {
        id: 6,
        title: "بناء مسجد",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        organization: "orman",
        category: "بناء",
        secation: "Donations",
      },
    ],
  },

  resala: {
    logo: "../../../public/images.png",
    history: "جمعية رسالة للأعمال الخيرية هي جمعية خيرية إسلامية مصرية، تأسست عام 1999 كنشاط طلابي في كلية الهندسة بجامعة القاهرة ثم أشهرت كجمعية خيرية في 29/5/2000.",
    data: [
      {
        id: 1,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "اطعام",
        organization: "resala",
        secation: "Donations",
      },
      {
        id: 2,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "اطعام",
        organization: "resala",
        secation: "Donations",
      },
      {
        id: 3,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        place: "المنوفيه",
        number: "01277840406",
        tragetprice: 2700,
        pricenow: 1000,
        category: "اطعام",
        organization: "resala",
        secation: "Donations",
      },
      {
        id: 4,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "اطعام",
        organization: "resala",
        secation: "Donations",
      },
      {
        id: 5,
        title: "توزيع شنطه رمضان",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "اطعام",
        organization: "resala",
        secation: "Donations",
      },
      {
        id: 6,
        title: "كفاله ايتام",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "كفاله",
        organization: "resala",
        secation: "Donations",
      },
      {
        id: 6,
        title: "بناء مسجد",
        image: "../../../public/P01131.jpg",
        tragetprice: 2700,
        place: "المنوفيه",
        number: "01277840406",
        pricenow: 1000,
        category: "بناء",
        organization: "resala",
        secation: "Donations",
      },
    ],
  },
};
